### ISSUE TITLE
npm start doesn't work on Ubuntu 15.04 with events.js:154 error

### ISSUE THREAD

**Issue by LaurensBER** [davezuko/react-redux-starter-kit#565]
Hi, 

I've tried running this clean (git clone/npm install/npm start) on Ubuntu 15.04 (with node 5.6.0 and npm 3.6.0) and I got the following output:

npm start

> > react-redux-starter-kit@1.0.0 start /home/laurens/dev/react-redux-starter-kit
> > better-npm-run start
> 
> running better-npm-run in /home/laurens/dev/react-redux-starter-kit
> Executing script: start
> 
> to be executed: babel-node bin/server 
>   app:config Create configuration. +0ms
>   app:config Apply environment overrides for NODE_ENV "development". +2ms
>   app:webpack:config Create configuration. +720ms
>   app:webpack:config Enable plugins for live development (HMR, NoErrors). +1ms
>   app:server:webpack-dev Enable webpack dev middleware. +178ms
>   app:server:webpack-hmr Enable Webpack Hot Module Replacement (HMR). +28ms
>   app:bin:server Server is now running at localhost:3000. +6ms
> events.js:154
>       throw er; // Unhandled 'error' event
>       ^
> 
> Error: listen EADDRINUSE :::3000
>     at Object.exports._errnoException (util.js:856:11)
>     at exports._exceptionWithHostPort (util.js:879:20)
>     at Server._listen2 (net.js:1227:14)
>     at listen (net.js:1263:10)
>     at Server.listen (net.js:1359:5)
>     at Application.listen (/home/laurens/dev/react-redux-starter-kit/node_modules/koa/lib/application.js:63:26)
>     at Object.<anonymous> (server.js:9:8)
>     at Module._compile (module.js:413:34)
>     at loader (/home/laurens/dev/react-redux-starter-kit/node_modules/babel-register/lib/node.js:128:5)
>     at Object.require.extensions.(anonymous function) [as .js] (/home/laurens/dev/react-redux-starter-kit/node_modules/babel-register/lib/node.js:138:7)
>     at Module.load (module.js:357:32)
>     at Function.Module._load (module.js:314:12)
>     at Function.Module.runMain (module.js:447:10)
>     at /home/laurens/dev/react-redux-starter-kit/node_modules/babel-cli/lib/_babel-node.js:161:27
>     at Object.<anonymous> (/home/laurens/dev/react-redux-starter-kit/node_modules/babel-cli/lib/_babel-node.js:162:7)
>     at Module._compile (module.js:413:34)
> 
> npm ERR! Linux 3.19.0-49-generic
> npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
> npm ERR! node v5.6.0
> npm ERR! npm  v3.6.0
> npm ERR! code ELIFECYCLE
> npm ERR! react-redux-starter-kit@1.0.0 start: `better-npm-run start`
> npm ERR! Exit status 1
> npm ERR! 
> npm ERR! Failed at the react-redux-starter-kit@1.0.0 start script 'better-npm-run start'.
> npm ERR! Make sure you have the latest version of node.js and npm installed.
> npm ERR! If you do, this is most likely a problem with the react-redux-starter-kit package,
> npm ERR! not with npm itself.
> npm ERR! Tell the author that this fails on your system:
> npm ERR!     better-npm-run start
> npm ERR! You can get information on how to open an issue for this project with:
> npm ERR!     npm bugs react-redux-starter-kit
> npm ERR! Or if that isn't available, you can get their info via:
> npm ERR!     npm owner ls react-redux-starter-kit
> npm ERR! There is likely additional logging output above.
> 
> npm ERR! Please include the following file with any support request:
> npm ERR!     /home/laurens/dev/react-redux-starter-kit/npm-debug.log

npm-debug.log:

> 0 info it worked if it ends with ok
> 1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'start' ]
> 2 info using npm@3.6.0
> 3 info using node@v5.6.0
> 4 verbose run-script [ 'prestart', 'start', 'poststart' ]
> 5 info lifecycle react-redux-starter-kit@1.0.0~prestart: react-redux-starter-kit@1.0.0
> 6 silly lifecycle react-redux-starter-kit@1.0.0~prestart: no script for prestart, continuing
> 7 info lifecycle react-redux-starter-kit@1.0.0~start: react-redux-starter-kit@1.0.0
> 8 verbose lifecycle react-redux-starter-kit@1.0.0~start: unsafe-perm in lifecycle true
> 9 verbose lifecycle react-redux-starter-kit@1.0.0~start: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/home/laurens/dev/react-redux-starter-kit/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games
> 10 verbose lifecycle react-redux-starter-kit@1.0.0~start: CWD: /home/laurens/dev/react-redux-starter-kit
> 11 silly lifecycle react-redux-starter-kit@1.0.0~start: Args: [ '-c', 'better-npm-run start' ]
> 12 silly lifecycle react-redux-starter-kit@1.0.0~start: Returned: code: 1  signal: null
> 13 info lifecycle react-redux-starter-kit@1.0.0~start: Failed to exec start script
> 14 verbose stack Error: react-redux-starter-kit@1.0.0 start: `better-npm-run start`
> 14 verbose stack Exit status 1
> 14 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:232:16)
> 14 verbose stack     at emitTwo (events.js:100:13)
> 14 verbose stack     at EventEmitter.emit (events.js:185:7)
> 14 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:24:14)
> 14 verbose stack     at emitTwo (events.js:100:13)
> 14 verbose stack     at ChildProcess.emit (events.js:185:7)
> 14 verbose stack     at maybeClose (internal/child_process.js:827:16)
> 14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
> 15 verbose pkgid react-redux-starter-kit@1.0.0
> 16 verbose cwd /home/laurens/dev/react-redux-starter-kit
> 17 error Linux 3.19.0-49-generic
> 18 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
> 19 error node v5.6.0
> 20 error npm  v3.6.0
> 21 error code ELIFECYCLE
> 22 error react-redux-starter-kit@1.0.0 start: `better-npm-run start`
> 22 error Exit status 1
> 23 error Failed at the react-redux-starter-kit@1.0.0 start script 'better-npm-run start'.
> 23 error Make sure you have the latest version of node.js and npm installed.
> 23 error If you do, this is most likely a problem with the react-redux-starter-kit package,
> 23 error not with npm itself.
> 23 error Tell the author that this fails on your system:
> 23 error     better-npm-run start
> 23 error You can get information on how to open an issue for this project with:
> 23 error     npm bugs react-redux-starter-kit
> 23 error Or if that isn't available, you can get their info via:
> 23 error     npm owner ls react-redux-starter-kit
> 23 error There is likely additional logging output above.
> 24 verbose exit [ 1, true ]

I've removed the default NodeJS version on Ubuntu (because it doesn't meet the minimum requirements) and upgraded to 5.6.5:

> laurens@laurens-XPS-13-9343:[~/dev/react-redux-starter-kit](bugfix/INCINTEL-119-feedback-verbeteringen): node --version
> v5.6.0
> laurens@laurens-XPS-13-9343:[~/dev/react-redux-starter-kit](bugfix/INCINTEL-119-feedback-verbeteringen): nodejs --version
> bash: /usr/bin/nodejs: No such file or directory

I can't find anything about this error on the internet so I'm putting this here as a reference. I'll update this if I figure out what's wrong

**Comment by LaurensBER** [comment]
Ah, I feel pretty stupid now but turns out this error was due something else running on port 3000. Would it be a good idea to handle these errors in a bit more newbie friendly way? It is after all a starters kit.

**Comment by davezuko** [comment]
@LaurensBER glad you figured it out. Honestly it's a fairly instructive error message, but I'll see if there's anything that can be done to produce even friendlier error messages. Closing this for now, though, since there's no actual issue. I'll update this issue if/when those improvements are made.
