### ISSUE TITLE
fail with current version of react-redux 

### ISSUE THREAD

**Issue by agdolla** [davezuko/react-redux-starter-kit#2]
If I try to upgrade to the current version of react-redux, which is 0.5.3 from the version specified in package.json (0.2.2) then the sample app fails to start:
Uncaught TypeError: (0 , _reactRedux.provide) is not a function

**Comment by davezuko** [comment]
Hey, just went and updated react-redux to ^0.5.0 and made the necessary API changes to Provider and how devTools renders. There's still a few things I have to tweak to make them 100% follow the "Redux way", but this should solve your problem for now.

Let me know if you're still having issues; I'll give it about a day before closing this in case there happen to be some other breaking changes that I missed.

**Comment by agdolla** [comment]
:+1:

**Comment by davezuko** [comment]
Just wanted to add that I've since updated react-redux to 0.6.0 which was released a couple hours ago!

**Comment by davezuko** [comment]
Closing this since no new issues from the upgrade seem to have popped up.
